---
# tasks file for kibana





- name: Install apt package requirements
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - gpg-agent
    - curl
    - procps
    - net-tools
    - gnupg
    - unzip

- name: Install kibana
  block:
    - name: Import kibana GPG Key
      ansible.builtin.shell: "curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"
    - name: Add kibana APT Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: "elastic-8.x.list"
    - name: Install kibana package
      ansible.builtin.apt:
        name: kibana
        state: present



- name: update host entry for elasticserach domain
  ansible.builtin.shell: echo "{{elastic_ip}} {{elastic_domain}}" | tee -a /etc/hosts
- name: update host entry for kibana domain
  ansible.builtin.shell: echo "{{kibana_ip}} {{kibana_domain}}" | tee -a /etc/hosts





- name: ansible copy file from remote to local.
  copy:
    src: ../templates/kibana.zip
    dest: /etc/kibana/kibana.zip




- name: Certificate extract for Elasticsearch
  ansible.builtin.shell: unzip /etc/kibana/kibana.zip -d /etc/kibana/certs/

- name: ansible copy file from remote to local.
  copy:
    src: ../templates/elastic_ca.crt
    dest: /etc/kibana/certs/elastic_ca.crt



- name: Clean and replace kibana.yml 
  ansible.builtin.template:
    src: kibana.yml.j2  # Path to your template file
    dest: /etc/kibana/kibana.yml




- name: Enable and start kibana service
  service:
    name: kibana
    state: restarted    