---

#tasks file for elasticsearch



- name: Install apt package requirements
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - gpg-agent
    - curl
    - procps
    - net-tools
    - gnupg
    - unzip




- name: Install Elasticsearch
  block:
    - name: elasticsearch-install | Import Elasticsearch GPG Key
      ansible.builtin.shell: "curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"
    - name: Add Elasticsearch APT Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: "elastic-8.x.list"
    - name: Install Elasticsearch package
      ansible.builtin.apt:
        name: elasticsearch
        state: present


- name: update host entry
  ansible.builtin.shell: echo "{{elastic_ip}} {{elastic_domain}}" | tee -a /etc/hosts

- name: Update JVM 
  ansible.builtin.shell: |
    sed -i -e 's/^## -Xms.*/-Xms{{xms}}/' -e 's/^## -Xmx.*/-Xmx{{xmx}}/' /etc/elasticsearch/jvm.options


- name: Clean and replace kibana.yml 
  ansible.builtin.template:
    src: elasticsearch.yml.j2  # Path to your template file
    dest: /etc/elasticsearch/elasticsearch.yml

- name: CA generation for elasticsearch & kibana
  ansible.builtin.shell: |
    /usr/share/elasticsearch/bin/elasticsearch-certutil ca --pem --out /etc/elasticsearch/certs/ca.zip
    unzip /etc/elasticsearch/certs/ca.zip -d /etc/elasticsearch/certs/




- name:  Certificate generation for elasticsearch 
  ansible.builtin.shell: |
    /usr/share/elasticsearch/bin/elasticsearch-certutil cert \
      --out /etc/elasticsearch/certs/elastic.zip \
      --name elastic \
      --ca-cert /etc/elasticsearch/certs/ca/ca.crt \
      --ca-key /etc/elasticsearch/certs/ca/ca.key \
      --dns {{elastic_domain}} \
      --ip {{elastic_ip}} \ 
      --pem;

- name: Certificate extract for Elasticsearch
  ansible.builtin.shell: unzip /etc/elasticsearch/certs/elastic.zip -d /etc/elasticsearch/certs/


- name:  Certificate generation for kibana 
  ansible.builtin.shell: |
    /usr/share/elasticsearch/bin/elasticsearch-certutil cert \
      --out /etc/elasticsearch/certs/kibana.zip \
      --name elastic \
      --ca-cert /etc/elasticsearch/certs/ca/ca.crt \
      --ca-key /etc/elasticsearch/certs/ca/ca.key \
      --dns {{kibana_domain}} \
      --ip {{kibana_ip}} \
      --pem;


- name:  Certificate certificate file permission fix
  ansible.builtin.shell: |
    chown -R elasticsearch:elasticsearch /etc/elasticsearch/certs


- name: Enable and start Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes


- name: Reset Elasticsearch password for 'elastic' user
  shell: |
    printf "{{ elastic_pass }}\n{{ elastic_pass }}" | /usr/share/elasticsearch/bin/elasticsearch-reset-password -b -i -u elastic 

- name: Reset Elasticsearch password for 'kibana' user
  shell: |
    printf "{{ kibana_pass }}\n{{ kibana_pass }}" | /usr/share/elasticsearch/bin/elasticsearch-reset-password -b -i -u kibana 


- name: ansible copy file from remote to local.
  fetch:
    src: /etc/elasticsearch/certs/kibana.zip
    dest: ../templates/kibana.zip
    flat: yes




- name: Enable and start Elasticsearch service
  service:
    name: elasticsearch
    state: restarted

